version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wallet-network
    depends_on:
      - wallet-next
      - wallet-node

  wallet-next:
    build: 
      context: ./wallet-next
    networks:
      - wallet-network

  wallet-node:
    build: 
      context: ./wallet-node
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge